# Generated by Django 3.1.3 on 2020-11-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Unidade', 'Unidade'), ('Pacote', 'Pacote'), ('Lata', 'Lata'), ('Caixa', 'Caixa'), ('Kg', 'Kg')], default='Unidade', max_length=10),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receita')),
            ],
        ),
    ]
