# Generated by Django 3.1.3 on 2020-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201127_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('Unidade', 'Unidade'), ('Pacote', 'Pacote'), ('Lata', 'Lata'), ('Caixa', 'Caixa'), ('Kg', 'Kg')], default='Unidade', max_length=10),
        ),
    ]
