# Generated by Django 3.1.4 on 2020-12-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201127_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
