# Generated by Django 3.1.3 on 2020-11-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20201114_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Un', 'Unidades'), ('Pc', 'Pacotes'), ('Lt', 'Latas'), ('Cx', 'Caixas')], default='Un', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
