# Generated by Django 3.1.4 on 2020-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201203_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
